ingress:
  host: bananaci.local

nginx:
  name: web-nginx
  image:
    pullPolicy: IfNotPresent
    repository: nginx
    tag: latest
  port:
    http: 80

rails:
  name: application-rails
  image:
    pullPolicy: IfNotPresent
    repository: ruby
    tag: 2.6-slim
  port:
    http: 3000
  dbHost: 3306

mysql:
  name: database-mysql
  image:
    pullPolicy: IfNotPresent
    repository: mysql
    tag: latest
  env:
    mysqlRootPassword: 
  port: 3306

postgres:
  name: database-postgres
  image:
    pullPolicy: IfNotPresent
    repository: postgres
    tag: latest
  env:
  port: 5432
