apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rails.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rails.name" . }}
    helm.sh/chart: {{ include "rails.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: webserver

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rails.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: webserver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rails.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: webserver
    spec:
      volumes:
        - name: sockets
          emptyDir: {}
      containers:
        - name: {{ .Values.nginx.name }}
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            # service から受けるポート
            - name: http
              containerPort: {{ .Values.nginx.port.http }}
          volumeMounts:
            - mountPath: /sockets
              name: sockets

        - name: {{ .Values.rails.name }}
          image: "{{ .Values.rails.image.repository }}:{{ .Values.rails.image.tag }}"
          # デフォルトで pull しにいってコケるので Never させないようにする
          imagePullPolicy: {{ .Values.rails.image.pullPolicy }}
          env:
            - name: DB_HOST
              value: "{{ .Values.rails.dbHost }}"

          volumeMounts:
            - mountPath: /sockets
              name: sockets

