apiVersion: v1
kind: Service
metadata:
  name: {{ include "rails.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rails.name" . }}
    helm.sh/chart: {{ include "rails.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  # ingress 経由なのでクラスタ内に閉じておく
  type: ClusterIP
  selector:
    # これにマッチした pod に流す
    app.kubernetes.io/name: {{ include "rails.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      # 受信するポート
      port: 84
      # 送信するポート
      # Pod の port 名でも可
      targetPort: http
