apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rails.fullname" . }}-db
  labels:
    app.kubernetes.io/name: {{ include "rails.name" . }}-db
    helm.sh/chart: {{ include "rails.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: database

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rails.name" . }}-db
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: database

  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rails.name" . }}-db
        app.kubernetes.io/instance: {{ .Release.Name }}
        helm.sh/chart: {{ include "rails.chart" . }}
        app.kubernetes.io/component: database

    spec:
      containers:
        {{- with .Values.mysql }}
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          env:
          {{- with .env.mysqlRootPassword }}
            - name: "MYSQL_ROOT_PASSWORD"
              value: {{ .env.mysqlRootPassword }}
          {{- else }}
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
          {{- end }}
          {{- if .env.mysqlDatabase }}
            - name: MYSQL_DATABASE
              value: {{ .env.mysqlDatabase }}
          {{- end }}
          ports:
            - name: {{ .name }}
              containerPort: {{ .port }}
        {{- end }}

        {{- with .Values.postgres }}
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          env:
            {{- range $var, $val := .env }}
            - name: {{ $var }}
              value: {{ $val }}
            {{- end }}
        {{- end }}
