apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rails.fullname" . }}-db
  labels:
    app.kubernetes.io/name: {{ include "rails.name" . }}-db
    helm.sh/chart: {{ include "rails.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: database

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rails.name" . }}-db
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: database

  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rails.name" . }}-db
        app.kubernetes.io/instance: {{ .Release.Name }}
        helm.sh/chart: {{ include "rails.chart" . }}
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: {{ .Values.db.name }}
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          env:
          {{ with .Values.db.env.mysqlRootPassword }}
            - name: "MYSQL_ROOT_PASSWORD"
              value: {{ .Values.db.env.mysqlRootPassword }}
          {{ else }}
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
          {{ end }}
          {{- if .Values.db.env.mysqlDatabase }}
            - name: MYSQL_DATABASE
              value: {{ .Values.db.env.mysqlDatabase }}
          {{- end }}

          ports:
            - name: mysql
              containerPort: {{ .Values.db.port }}

